services:
  - type: web
    name: scorenova-telegram-webapp
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_BOT_USERNAME
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
